export const moviesOfTwentyTwenty = [
    "Birds of Prey",
    "Sonic the Hedgehog",
    "Fantasy Island",
    "To All the Boys: P.S. I Still Love You",
    "Dolittle",
    "Vtorzhenie",
    "Ghost Stories",
    "Horse Girl",
    "The Windermere Children",
    "Nine Days",
    "Charm City Kings",
    "Sylvieâ€™s Love",
    "The Hunt",
    "Trolls World Tour",
    "Bad Boys for Life",
    "Emma.",
    "I Love Tropoja",
    "Milea: Suara dari Dilan",
    "Gretel & Hansel",
    "Downhill",
    "Malang - Unleash the Madness",
    "Jaanu",
    "The Invisible Man",
    "Color Out of Space",
    "Street Dancer 3D",
    "John Henry",
    "Panga",
    "Zola",
    "After We Collided",
    "Antebellum",
    "The Call of the Wild",
    "The Night Clerk",
    "Come to Daddy",
    "365 Days",
    "Shikara",
    "Hacked",
    "Waiting for Anya",
    "Two/One",
    "Varane Avashyamund",
    "Ayyappanum Koshiyum",
    "Tenet",
    "The Photograph",
    "Love Aaj Kal",
    "Buffaloed",
    "VFW",
    "The Last Thing He Wanted",
    "World Famous Lover",
    "Isi & Ossi",
    "Come as You Are",
    "Spy Intervention",
    "First Lady",
    "Mafia Inc",
    "Wonder Woman 1984",
    "Underwater",
    "Darbar",
    "Mulan",
    "The Rhythm Section",
    "The Assistant",
    "Jawaani Jaaneman",
    "Coda",
    "Brahms: The Boy II",
    "Kill Chain",
    "Timmy Failure: Mistakes Were Made",
    "The Lodge",
    "The Way Back",
    "Bloodshot",
    "10 Things We Should Do Before We Break Up",
    "The Last Full Measure",
    "The Turning",
    "Enter the Fat Dragon",
    "Modo AviÃ£o",
    "D-Day",
    "A Fall from Grace",
    "Disturbing the Peace",
    "The Host",
    "Dragonheart Vengeance",
    "Bill & Ted Face the Music",
    "The War with Grandpa",
    "Onward",
    "The Nothing",
    "Resistance",
    "The New Mutants",
    "The Grudge",
    "True History of the Kelly Gang",
    "Like a Boss",
    "My Spy",
    "The Assent",
    "Promising Young Woman",
    "The Vast of Night",
    "Wendy",
    "All the Bright Places",
    "Burden",
    "Mortal",
    "Impractical Jokers: The Movie",
    "Shubh Mangal Zyada Saavdhan",
    "Scoob",
    "Monster Hunter",
    "Spenser Confidential",
    "Military Wives",
    "Escape from Pretoria",
    "Run This Town",
    "First Cow",
    "Beneath Us",
    "The Burnt Orange Heresy",
    "The Banker",
    "I Still Believe",
    "Misbehaviour",
    "The King of Staten Island",
    "Artemis Fowl",
    "Ammonite",
    "Mank",
    "Dreamland",
    "Tanhaji: The Unsung Warrior",
    "The Murder of Nicole Brown Simpson",
    "Inherit the Viper",
    "Sarileru Neekevvaru",
    "Chhapaak",
    "The Secret Garden",
    "The Spongebob Movie: Sponge on the Run",
    "Spree",
    "Project Power",
    "Palm Springs",
    "Capone",
    "Greyhound",
    "The Old Guard",
    "Most Wanted",
    "Darlin'",
    "Camp Cold Brook",
    "The Tax Collector",
    "An American Pickle",
    "Enola Holmes",
    "Enola Holmes",
    "The Kissing Booth 2",
    "Cupid",
    "Alien Outbreak",
    "Agramon's Gate",
    "Soul",
    "News of the World",
    "One Night in Miami",
    "We Can Be Heroes",
    "The Roads Not Taken",
    "Never Rarely Sometimes Always",
    "Minamata",
    "Big Time Adolescence",
    "The Shadow of Violence",
    "Lost Transmissions",
    "The Lovebirds",
    "Hamilton",
    "Relic",
    "Hamilton",
    "Viena and the Fantomes",
    "The Trial of the Chicago 7",
    "Kajillionaire",
    "The Witches",
    "Irresistible",
    "The One and Only Ivan",
    "The Croods: A New Age",
    "Ma Rainey's Black Bottom",
    "Spycies",
    "The Secret: Dare to Dream",
    "Jiu Jitsu",
    "Sound of Metal",
    "The Last Vermeer",
    "The Devil All the Time",
    "Shirley",
    "Hubie Halloween",
    "Shimla Mirchi",
    "Rocket Hunter",
    "Ana",
    "Untitled Drake Doremus Project",
    "The Outpost",
    "Sergio",
    "Two of Us",
    "Lost Girls",
    "The Glorias",
    "Saint Maud",
    "Ala Vaikunthapurramuloo",
    "Train to Busan Presents: Peninsula",
    "Stargirl",
    "The Father",
    "Happiest Season",
    "Miss Fisher and the Crypt of Tears",
    "Vanguard",
    "The Boys in the Band",
    "Extraction",
    "Possessor",
    "Falling",
    "On The Rocks",
    "Rambo",
    "Save Yourselves!",
    "Cut Throat City",
    "Come Away",
    "The Comeback Trail",
    "The Prom",
    "Eurovision Song Contest: The Story of Fire Saga",
    "Bone Breaker",
    "Angels Fallen",
    "Bulletproof 2",
    "The Mercenary",
    "Love and Monsters",
    "Rebecca",
    "The Moon and the Sun",
    "InstaFame",
    "Nightlife",
    "Baaghi 3",
    "Sufna",
    "Hillbilly Elegy",
    "Ava",
    "Force of Nature",
    "Synchronic",
    "Hard Kill",
    "Black Bear",
    "I'm Thinking of Ending Things",
    "Jungleland",
    "How to Build a Girl",
    "The Midnight Sky",
    "Let Them All Talk",
    "The Very Excellent Mr. Dundee",
    "Life in a Year",
    "Black Beauty",
    "Breach",
    "Bad Trip",
    "The Babysitter: Killer Queen",
    "Let Him Go",
    "Unhinged",
    "The High Note",
    "Joe and Jadin Bell",
    "Honest Thief",
    "Lost Girls and Love Hotels",
    "Survive the Night",
    "Shadow in the Cloud",
    "You Should Have Left",
    "Arkansas",
    "Inheritance",
    "Greenland",
    "Seized",
    "The Rental",
    "Superintelligence",
    "Nomadland",
    "Valley Girl",
    "The Secrets We Keep",
    "Debt Collectors",
];
